<a href="https://colab.research.google.com/github/angelahjhong/project-2/blob/main/CHD_testcleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/content/fhs_test.csv')
df.head()

Unnamed: 0  sex  age  education  currentSmoker  cigsPerDay  BPMeds  \
0         674    0   58        1.0              1        20.0     0.0   
1        4070    0   51        3.0              0         0.0     0.0   
2        3150    0   44        2.0              1         9.0     0.0   
3        1695    0   40        2.0              1        20.0     0.0   
4        2692    1   58        2.0              1        20.0     0.0   

   prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                0             0         0      NaN  126.0   77.0  30.08   
1                0             0         0    264.0  135.0   83.0  26.68   
2                0             1         0      NaN  147.5   96.0  30.57   
3                0             0         0    271.0  138.5   88.0  27.24   
4                0             0         0    207.0  110.0   80.0  23.55   

   heartRate  glucose  TenYearCHD  
0       78.0      NaN           0  
1       60.0     74.0           0  
2       78.0      NaN           1  
3       80.0      NaN           1  
4       78.0     78.0           0

In [4]:
df.columns

Index(['Unnamed: 0', 'sex', 'age', 'education', 'currentSmoker', 'cigsPerDay',
       'BPMeds', 'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol',
       'sysBP', 'diaBP', 'BMI', 'heartRate', 'glucose', 'TenYearCHD'],
      dtype='object')

In [5]:
df.shape

(1060, 17)

In [7]:
# sex variable does not need cleaning (0=female, 1=male)
df['sex'].value_counts()

sex
0    617
1    443
Name: count, dtype: int64

In [10]:
# age variable does not need cleaning
df['age'].unique()

array([58, 51, 44, 40, 53, 41, 50, 42, 45, 52, 57, 46, 38, 47, 48, 56, 66,
       68, 59, 54, 49, 39, 61, 62, 67, 43, 64, 37, 34, 35, 55, 36, 63, 65,
       60, 69])

In [13]:
# currentSmoker does not need cleaning (0=not smoking, 1=smoking)
df['currentSmoker'].value_counts()

currentSmoker
1    534
0    526
Name: count, dtype: int64

In [15]:
# cigsPerDay needs to remove nan from the data
df['cigsPerDay'].unique()

array([20.,  0.,  9.,  5., 35., 30., 10., 40.,  1., 15.,  3., 45., 25.,
       43., 17., 23., 13., 18., 50.,  4.,  2.,  6., nan, 60.,  8., 12.,
        7., 14.])

In [18]:
# there are 5 nan values
nan_cigs = df['cigsPerDay'].isna().sum()
print(nan_cigs)

5


In [19]:
# the median number of cigs per day is 1
median_cigs = df['cigsPerDay'].median()
print(median_cigs)

1.0


In [24]:
# replace all nan values with the median to ensure no skewed data
df['cigsPerDay'] = df['cigsPerDay'].fillna('1.0')
df['cigsPerDay'].unique()

array([20.0, 0.0, 9.0, 5.0, 35.0, 30.0, 10.0, 40.0, 1.0, 15.0, 3.0, 45.0,
       25.0, 43.0, 17.0, 23.0, 13.0, 18.0, 50.0, 4.0, 2.0, 6.0, '1.0',
       60.0, 8.0, 12.0, 7.0, 14.0], dtype=object)

In [30]:
# prevalentStroke variable does not need cleaning
df['prevalentStroke'].value_counts()

prevalentStroke
0    1056
1       4
Name: count, dtype: int64

In [33]:
# prevalentHyp variable does not need cleaning
df['prevalentHyp'].value_counts()

prevalentHyp
0    764
1    296
Name: count, dtype: int64

In [37]:
# diabetes variable does not need cleaning
df['diabetes'].value_counts()

diabetes
0    1034
1      26
Name: count, dtype: int64

In [39]:
df['BMI'].unique()

array([30.08, 26.68, 30.57, 27.24, 23.55, 25.82, 27.8 , 21.98, 29.8 ,
       25.77, 27.3 , 22.32, 33.32, 27.66, 28.57, 24.19, 39.6 , 29.84,
       23.45, 29.08, 20.89, 22.83, 25.09, 28.3 , 23.26, 25.54, 27.56,
       25.5 , 26.48, 25.94, 24.68, 27.22, 26.83, 36.12, 21.02, 32.84,
       23.87, 27.93, 20.68, 22.18, 21.67, 19.72, 24.22, 22.14, 30.74,
       25.65, 23.33, 21.3 , 27.89, 29.5 , 29.38, 20.52, 28.27, 22.35,
       25.75, 28.04, 22.19, 26.07, 26.89, 24.42, 26.84, 20.85, 23.64,
       24.32, 21.35, 20.39, 20.72, 24.35, 30.34, 35.35, 29.48, 26.91,
       26.87, 28.44, 20.02, 28.33, 21.5 , 21.19, 26.59, 25.67, 23.19,
       21.14, 25.48, 28.55, 25.71, 23.09, 21.45, 24.24, 30.16, 23.22,
       20.51, 32.52, 21.11, 26.13, 24.47, 28.4 , 24.71, 32.35, 28.67,
       24.72, 29.19, 29.07, 25.84, 24.49, 20.12, 26.18, 22.85, 36.21,
       27.1 , 24.69, 25.11, 29.43, 21.34, 34.84, 30.43, 25.04, 22.34,
       21.93, 29.42, 17.5 , 23.67, 24.1 , 23.27, 27.45, 24.77, 24.94,
       25.18, 29.35,

In [40]:
nan_bmi = df['BMI'].isna().sum()
print(nan_bmi)

4


In [41]:
median_bmi = df['BMI'].median()
print(median_bmi)

25.14


In [42]:
df['BMI'] = df['BMI'].fillna('25.14')
df['BMI'].unique()

array([30.08, 26.68, 30.57, 27.24, 23.55, 25.82, 27.8, 21.98, 29.8, 25.77,
       27.3, 22.32, 33.32, 27.66, 28.57, 24.19, 39.6, 29.84, 23.45, 29.08,
       20.89, 22.83, 25.09, 28.3, 23.26, 25.54, 27.56, 25.5, 26.48, 25.94,
       24.68, 27.22, 26.83, 36.12, 21.02, 32.84, 23.87, 27.93, 20.68,
       22.18, 21.67, 19.72, 24.22, 22.14, 30.74, 25.65, 23.33, 21.3,
       27.89, 29.5, 29.38, 20.52, 28.27, 22.35, 25.75, 28.04, 22.19,
       26.07, 26.89, 24.42, 26.84, 20.85, 23.64, 24.32, 21.35, 20.39,
       20.72, 24.35, 30.34, 35.35, 29.48, 26.91, 26.87, 28.44, 20.02,
       28.33, 21.5, 21.19, 26.59, 25.67, 23.19, 21.14, 25.48, 28.55,
       25.71, 23.09, 21.45, 24.24, 30.16, 23.22, 20.51, 32.52, 21.11,
       26.13, 24.47, 28.4, 24.71, 32.35, 28.67, 24.72, 29.19, 29.07,
       25.84, 24.49, 20.12, 26.18, 22.85, 36.21, 27.1, 24.69, 25.11,
       29.43, 21.34, 34.84, 30.43, 25.04, 22.34, 21.93, 29.42, 17.5,
       23.67, 24.1, 23.27, 27.45, 24.77, 24.94, 25.18, 29.35, 25.25,
       28.28

In [45]:
df['glucose'].unique()

array([ nan,  74.,  78.,  83.,  73.,  82.,  70.,  87., 205.,  64.,  69.,
        80.,  79.,  62.,  90.,  85.,  58., 119.,  67., 163.,  66.,  77.,
        72., 143.,  71.,  99.,  75.,  91.,  89.,  63., 113., 122., 114.,
       100., 112.,  92., 102., 104.,  61., 108.,  81., 177.,  76.,  88.,
        60.,  68., 386.,  93., 117.,  95.,  59., 124., 107.,  65., 103.,
       137.,  86.,  84.,  45.,  98.,  57., 132., 140.,  94., 110.,  97.,
        55., 115., 325., 368.,  96.,  52.,  44., 170., 120., 123., 101.,
       394.,  53., 130., 223.,  56., 126., 105., 156., 136., 183., 173.,
       155., 106., 145.])

In [47]:
nan_glucose = df['glucose'].isna().sum()
print(nan_glucose)

103


In [48]:
median_glucose = df['glucose'].median()
print(median_glucose)

78.0


In [49]:
df['glucose'] = df['glucose'].fillna('78.0')
df['glucose'].unique()

array(['78.0', 74.0, 78.0, 83.0, 73.0, 82.0, 70.0, 87.0, 205.0, 64.0,
       69.0, 80.0, 79.0, 62.0, 90.0, 85.0, 58.0, 119.0, 67.0, 163.0, 66.0,
       77.0, 72.0, 143.0, 71.0, 99.0, 75.0, 91.0, 89.0, 63.0, 113.0,
       122.0, 114.0, 100.0, 112.0, 92.0, 102.0, 104.0, 61.0, 108.0, 81.0,
       177.0, 76.0, 88.0, 60.0, 68.0, 386.0, 93.0, 117.0, 95.0, 59.0,
       124.0, 107.0, 65.0, 103.0, 137.0, 86.0, 84.0, 45.0, 98.0, 57.0,
       132.0, 140.0, 94.0, 110.0, 97.0, 55.0, 115.0, 325.0, 368.0, 96.0,
       52.0, 44.0, 170.0, 120.0, 123.0, 101.0, 394.0, 53.0, 130.0, 223.0,
       56.0, 126.0, 105.0, 156.0, 136.0, 183.0, 173.0, 155.0, 106.0,
       145.0], dtype=object)

In [52]:
# TenYearCHD variable does not need cleaning
df['TenYearCHD'].value_counts()

TenYearCHD
0    903
1    157
Name: count, dtype: int64